accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as dj_auth_views
from django.urls import reverse_lazy

from . import views

urlpatterns = [
    url(r'^profile/$', views.ProfileView.as_view(), name='signup'),

    # url(r'^signup/$', views.signup, name='signup'),
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),

    # login / logout urls
    url(r'^login/$', dj_auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', dj_auth_views.LogoutView.as_view(), name='logout'),

    # change password urls
    url(r'^password-change/$', dj_auth_views.PasswordChangeView.as_view(
        template_name='accounts/password_change_form.html', success_url=reverse_lazy('accounts:password_change_done')),
        name='password_change'),
    url(r'^password-change/done/$',
        dj_auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
        name='password_change_done'),

    # restore password urls
    url(r'^password-reset/$',
        dj_auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset_form.html',
            email_template_name='accounts/password_reset_email.html',
            subject_template_name='accounts/password_reset_subject.txt',
            success_url=reverse_lazy('accounts:password_reset_done')
        ),
        name='password_reset'),
    url(r'^password-reset/done/$',
        dj_auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        dj_auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm'),
    url(r'^password-reset/complete/$',
        dj_auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),

    # user profiles
    # url(r'^users/$', views.user_list, name='user_list'),
    # url(r'^users/follow/$', views.user_follow, name='user_follow'),
    # url(r'^users/(?P<username>[-\w]+)/$', views.user_detail, name='user_detail'),
]

index/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='home'),
]

qvandares/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^currency/', include('currency.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url('^api/v1/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^lodging/', include('lodging.urls', namespace='lodging', app_name='lodging')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^', include('index.urls', namespace='index', app_name='index')),
)

accounts/models.py
# from django.contrib.auth.models import User as DjangoUserModel


# class User(DjangoUserModel):
#     class Meta:
#         proxy = True
#
#     def __str__(self):
#         return self.get_short_name() or self.email.split('@')[0]

accounts/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class SignUpForm(forms.ModelForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = ('first_name', 'email')

    def clean_password(self):
        password = self.cleaned_data.get("password")
        password_validation.validate_password(password, self.instance)
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = user.email
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

accounts/views.py
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from .forms import SignUpForm


class ProfileView(TemplateView):
    template_name = 'accounts/profile.html'


class SignUp(FormView):
    template_name = 'registration/signup.html'
    form_class = SignUpForm

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user)
        return redirect('index:home')


# def signup(request):
#     if request.method == 'POST':
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             auth_login(request, user)
#             return redirect('index:home')
#     else:
#         form = SignUpForm()
#     return render(request, 'registration/signup.html', {'form': form})

accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}
{% load i18n %}
{#{% block title %}Password changed{% endblock %}#}
{% block inside_header %}

{% endblock %}
{% block content %}
    <h1>{% trans 'Change you password' %}</h1>
    <p>{% trans 'Use the form below to change your password.' %}</p>
    <a href="{% url 'index:home' %}">{% trans 'Continue discovering...' %}</a>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends "base.html" %}
{% load i18n %}
{#{% block title %}Change you password{% endblock %}#}
{% block content %}
    <h1>{% trans 'Change you password' %}</h1>
    <p>{% trans 'Use the form below to change your password.' %}</p>
    <form method="post">
        {% include 'includes/form.html' %}
        <p><input type="submit" value="Change"></p>
        {% csrf_token %}
    </form>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
    <h1>Password set</h1>
    <p>Your password has been set. You can <a href="{% url "accounts:login"%}">log in now</a></p>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
    <h1>Reset your password</h1>
    {% if validlink %}
        <p>Please enter your new password twice:</p>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Change my password"/></p>
        </form>
    {% else %}
        <p>The password reset link was invalid, possibly because it has
            already been used. Please request a new password reset.</p>
    {% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
    <h1>Reset your password</h1>
    <p>We've emailed you instructions for setting your password.</p>
    <p>If you don't receive an email, please make sure you've entered
        the address you registered with.</p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the
link below:
{{ protocol }}://{{ domain }}{% url "accounts:password_reset_confirm" uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
    <h1>Forgotten your password?</h1>
    <p>Enter your e-mail address to obtain a new password.</p>
    <form method="post">
        {% include 'includes/form.html' %}
        <p><input type="submit" value="Send e-mail"></p>
        {% csrf_token %}
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block inside_header %}

{% endblock %}
{% block content %}
<h1>{{ user }}</h1>
    <a href="{% url 'accounts:password_change' %}">Change password</a>
{% endblock %}