index/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='home'),
]

qvandares/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^currency/', include('currency.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url('^api/v1/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^lodging/', include('lodging.urls', namespace='lodging', app_name='lodging')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),
    url(r'^', include('index.urls', namespace='index', app_name='index')),
)

templates/base.html
{% load static %}
{% load i18n %}
{% load meta %}
{% load currency %}
<!doctype html>
<html lang="en">

<head {% meta_namespaces %}>
    {% include "meta/meta.html" %}
    {#    <title>{% block title %}{% if page_title %}{{ page_title }} - {% endif %} qvandares{% endblock %}</title>#}
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="all">
    <link href="{% static 'css/qva.css' %}" type="text/css" rel="stylesheet" media="all">
    {% if DEBUG %}
        {% include 'includes/statics/css-dev.html' %}
    {% else %}
        {% include 'includes/statics/css-prod.html' %}
    {% endif %}
    <link href="{% static 'css/themify-icons.css' %}" type="text/css" rel="stylesheet" media="all">
    <link href="{% static 'libs/air-datepicker/datepicker.custom.min.css' %}" type="text/css" rel="stylesheet"
      media="all">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    {% if DEBUG %}
        {% include 'includes/statics/js-dev.html' %}
    {% else %}
        {% include 'includes/statics/js-prod.html' %}
    {% endif %}
{#    <script src="{% static 'js/modernizr.custom.js' %}"></script>#}

    <!--    <script src="libs/DjangoAjax.js"></script>-->
</head>

<body>
<div class="qva-top-nav">
    <div class="qva-top-nav-content">
        <ul class="top-menu">
            <li class="top-menu-login">
                {% if user.is_authenticated %}
                    <a class="qva-top-nav-elem qva-link">{{ user.first_name|capfirst }}</a>
                {% else %}
                <a class="qva-top-nav-elem qva-link" href="{% url 'accounts:signup' %}">sign up</a>
                <a class="qva-top-nav-elem login" href="{% url 'accounts:login' %}">sign in</a>
                {% endif %}
            </li>
            <li class="top-menu-lang">
                <form action="{% url 'set_language' %}" method="post" class="qva-top-nav-elem"
                      id="form-set-lang">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ request.path|slice:'3:' }}"/>
                    <select name="language" class="qva-top-menu-input qva-top-menu-select-lang" id="select-lang">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                    class="flag-icon flag-icon-es"
                                    selected="selected"{% endif %}>
                                {{ language.name_local|title }}
                            </option>
                        {% endfor %}
                    </select>
                </form>

            </li>

            <li class="top-menu-lang">
                <form class="qva-top-nav-elem" action="{% url 'set_currency' %}" method="post" id="form-set-currency">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ request.path|slice:'3:' }}"/>
                    <select name="currency" class="qva-top-menu-input qva-top-menu-select-lang">
                        {% get_available_currencies as available_currencies %}
                        {% get_current_currency as current_currency %}
                        {% for currency in available_currencies %}
                            <option value="{{ currency }}" {% if currency == current_currency %}selected="selected"{% endif %}>{{ currency }}</option>
                        {% endfor %}
                    </select>
                </form>
            </li>
            <li class="top-menu-search">
                <form class="qva-top-nav-elem">
                    <span class="ti-search lupa-icon"></span>
                    <input type="text" placeholder="Search..." class="qva-top-menu-input qva-top-menu-input-search">
                </form>
            </li>
        </ul>

    </div>
    <div class="clearfix"></div>
</div>
<!--banner-->
<div class="banner">
    <!--header-->
    <div class="header">
        <div class="container">
            <div class="header-logo">
                <img src="{% static 'images/logo1-1.png' %}" alt="qvandares" class="logo"/>
            </div>
            <div class="top-nav">
                <span class="menu"> </span>
                <ul class="nav1">
                    <li><a href="{% url 'index:home' %}" class="scroll {% if menu_link_active == 'home' %}active{% endif %}">{% trans 'HOME' %}</a></li>
                    <li><a href="#about" class="scroll">{% trans 'HOTELS' %}</a></li>
                    <li><a href="{% url 'lodging:home_list' %}" class="scroll {% if menu_link_active == 'homes' %}active{% endif %}">{% trans 'HOMES' %}</a></li>
                    <li><a href="#team" class="scroll">{% trans 'CUBANIA' %}</a></li>
                    <li><a href="#blog" class="scroll">{% trans 'TOURS' %}</a></li>
                    <li><a href="#contact" class="scroll">{% trans 'ABOUT US' %}</a></li>
                </ul>

            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <!--//header-->
    {% block inside_header %}
        <div class="container">
            <div class="banner-title">
{#  TODO: buscar frase inspiradora para viajar              #}
                <h5>GRAB YOUR ATTENTION</h5>
                <h1><span>TRAVELERS </span> REPOSE AND DREAM AMONG MY <span> LEAVES</span></h1>
                <div class="container-fluid">
                    <div class="row main-book-form">
                        <div class="container-fluid"></div>
                        <div class="col-md-4 col-xs-12 book-search">
                            <input type="text" class="input-search"
                                   placeholder="{% trans 'Hotels, Places, Tours...' %}">
                            <span class="ti-search book-lupa-icon"></span>
                        </div>
                        <div class="col-md-5 col-xs-12">
                            <input type="text" class="input-datepicker" id="booking-datepicker"
                                   placeholder="{% trans 'Arrival and Departure' %}">
                        </div>
                        <div class="col-md-3 col-xs-12 book-btn">
                            <div class="download">
                                <a href="#">{% trans 'Start booking now' %}</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    {% endblock inside_header %}
</div>
<!--//banner-->
{% block content %} {% endblock %}

<!--footer-->
<div class="footer">
    <div class="container">
        <div class="footer-grids">
            <div class="col-md-3 footer-logo">
                <a href="index.html"><img src="{% static 'images/logo1-1.png' %}" alt="logo" width="250"/></a>
                <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum
                    dolore.</p>
                <p class="logo-text">eugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
                    praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum
                    soluta</p>
            </div>
            <div class="col-md-3 recent-posts">
                <h4>{% trans 'TERMS OF SERVICES' %}</h4>
                <div class="recent-posts-text">
                    <p>Please read these Terms of Service carefully as they contain important information about your
                        legal rights, remedies and obligations. By accessing or using the Airbnb Platform, you agree to
                        comply with and be bound by these Terms of Service.</p>
                    <h5>Read more...</h5>
                </div>

            </div>
            <div class="col-md-3 recent-posts">
                <h4>FAQs</h4>
                <div class="recent-posts-text">
                    <p>How...</p>
                    <p>What...</p>
                    <p>When...</p>
                    <p>Where...</p>
                </div>
                <h5>Read all... </h5>
            </div>
            <div class="col-md-3 address">
                <h4>OUR ADDRESS</h4>
                <p>Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam
                    processus dynamicus, luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber
                    tempor cum soluta </p>
                <ul>
                    <li>poner aqui las redes sociales</li>
                    <li><span class="mail"></span><a href="mailto:example@email.com">mail@example.com</a></li>
                </ul>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!--//footer-->
<div class="footer-bottom">
    <p>© 2017 All rights reserved | Design by <a href="http://w3layouts.com/"> W3layouts</a></p>
</div>

<!--smooth-scrolling-of-move-up-->
<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!--//smooth-scrolling-of-move-up-->


{% block javascript %} {% endblock %}
<script>
    $(document).ready(function () {
        var $formSetLang = $('form#form-set-lang');
        var $formSetCurrency = $('form#form-set-currency');
        var $selectLang = $formSetLang.find('select#select-lang');
        var $selectCurrency = $formSetCurrency.find('select[name="currency"]');
        $selectLang.change(function () {
            $formSetLang.submit();
        });
        $selectCurrency.change(function () {
            $formSetCurrency.submit();
        });
        //script-for-menu -->
        $("span.menu").click(function () {
            $("ul.nav1").slideToggle(300, function () {
                // Animation complete.
            });
        });
        //script-for-menu -->
    })
</script>
</body>

</html>